# Generated by Django 5.2.7 on 2025-11-27 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(help_text='Número de identificación del asistente', max_length=50, unique=True, verbose_name='Identificación')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del asistente', max_length=200, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico del asistente', max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del asistente', max_length=20, null=True, verbose_name='Teléfono')),
                ('sede', models.CharField(blank=True, help_text='Sede a la que pertenece el asistente', max_length=100, null=True, verbose_name='Sede')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'db_table': 'asistentes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(choices=[('ENTRADA', 'Entrada al Evento'), ('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('REFRIGERIO', 'Refrigerio')], max_length=20, verbose_name='Tipo de Comida')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código QR')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_uso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to='event_management.asistente', verbose_name='Asistente')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['asistente__nombre_completo', 'tipo_comida'],
                'unique_together': {('asistente', 'tipo_comida')},
            },
        ),
    ]
