# Generated by Django 5.2.7 on 2026-01-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_evento_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='asistencia_qr',
            field=models.BooleanField(default=False, verbose_name='¿Asistencia por QR?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cantidad_refrigerios',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Refrigerios'),
        ),
        migrations.AddField(
            model_name='evento',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Flyer del Evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='requiere_refrigerio',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Refrigerio?'),
        ),
    ]
