# Generated by Django 5.2.7 on 2026-01-18 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_evento_asistencia_qr_evento_cantidad_refrigerios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigoqr',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Código QR', 'verbose_name_plural': 'Códigos QR'},
        ),
        migrations.AlterUniqueTogether(
            name='codigoqr',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to='event_management.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='codigoqr',
            name='asistente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to='event_management.asistente', verbose_name='Asistente Legacy'),
        ),
    ]
