# Generated by Django 5.2.7 on 2026-01-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_alter_codigoqr_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='detalles_refrigerios',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalles de Refrigerios'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cantidad_refrigerios',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Refrigerios (Total)'),
        ),
    ]
