# Generated by Django 5.2.7 on 2026-01-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_evento_detalles_refrigerios_evento_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='tipo_comida',
            field=models.CharField(max_length=100, verbose_name='Tipo de Comida'),
        ),
    ]
