# Generated by Django 5.2.7 on 2026-01-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0006_alter_codigoqr_tipo_comida'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='plantilla_certificado',
            field=models.FileField(blank=True, null=True, upload_to='plantillas_certificados/', verbose_name='Plantilla de Certificado (PDF)'),
        ),
    ]
