# Generated by Django 5.2.7 on 2026-01-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0007_evento_plantilla_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y Hora de Inicio'),
        ),
    ]
