# Generated by Django 5.2.7 on 2026-01-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Identificación')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('role', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Asistente', 'Asistente'), ('Docente', 'Docente'), ('Administrador', 'Administrador')], default='Estudiante', max_length=20)),
                ('dependency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dependencia')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
