# Generated by Django 5.2.4 on 2026-01-30 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(help_text='Número de identificación del asistente', max_length=50, unique=True, verbose_name='Identificación')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del asistente', max_length=200, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico del asistente', max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del asistente', max_length=20, null=True, verbose_name='Teléfono')),
                ('sede', models.CharField(blank=True, help_text='Sede a la que pertenece el asistente', max_length=100, null=True, verbose_name='Sede')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'db_table': 'asistentes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Identificación')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('role', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Asistente', 'Asistente'), ('Docente', 'Docente'), ('Administrador', 'Administrador')], default='Estudiante', max_length=20)),
                ('dependency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dependencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff')),
                ('verification_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Código de Verificación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Flyer del Evento')),
                ('requiere_refrigerio', models.BooleanField(default=False, verbose_name='¿Requiere Refrigerio?')),
                ('cantidad_refrigerios', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Refrigerios (Total)')),
                ('asistencia_qr', models.BooleanField(default=False, verbose_name='¿Asistencia por QR?')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('detalles_refrigerios', models.JSONField(blank=True, default=dict, verbose_name='Detalles de Refrigerios')),
                ('plantilla_certificado', models.FileField(blank=True, null=True, upload_to='plantillas_certificados/', verbose_name='Plantilla de Certificado (PDF)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Evento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(max_length=100, verbose_name='Tipo de Comida')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código QR')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_uso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso')),
                ('asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to='core.asistente', verbose_name='Asistente Legacy')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_qr', to='core.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Código QR',
                'verbose_name_plural': 'Códigos QR',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('asistio', models.BooleanField(default=False, verbose_name='¿Asistió?')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('evento', 'usuario')},
            },
        ),
    ]
