# Generated by Django 5.2.7 on 2026-01-31 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteActivoUnivalle',
            fields=[
                ('codigo_estudiante', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código Estudiante')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('correo', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Estudiante Activo',
                'verbose_name_plural': 'Estudiantes Activos',
                'db_table': 'estudiantes_activos_univalle',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del Programa')),
            ],
            options={
                'verbose_name': 'Programa Académico',
                'verbose_name_plural': 'Programas Académicos',
                'db_table': 'programas',
                'ordering': ['descripcion'],
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Asistente', 'Asistente'), ('Docente', 'Docente'), ('Coordinador', 'Coordinador'), ('Administrador', 'Administrador')], default='Estudiante', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='programas_dirigidos',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='core.programa', verbose_name='Programas Dirigidos'),
        ),
    ]
