# Generated by Django 5.2.7 on 2026-02-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estudianteactivounivalle_programa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='flyer',
        ),
        migrations.AddField(
            model_name='evento',
            name='flyer_content_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de contenido del flyer (MIME type)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='flyer_data',
            field=models.BinaryField(blank=True, help_text='Contenido binario de la imagen del flyer', null=True, verbose_name='Flyer del Evento (BLOB)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='flyer_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del archivo del flyer'),
        ),
    ]
