# Generated by Django 5.2.4 on 2026-02-04 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_flyer_blob_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteactivounivalle',
            name='programa',
            field=models.ForeignKey(blank=True, db_column='programa_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='core.programa', verbose_name='Programa Académico'),
        ),
    ]
