# Generated by Django 5.2.4 on 2026-02-05 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estudianteactivounivalle_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='config_certificado',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Configuración del Certificado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='plantilla_certificado',
            field=models.FileField(blank=True, null=True, upload_to='plantillas_certificados/', verbose_name='Plantilla de Certificado (Imagen/PDF)'),
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_blob', models.BinaryField(verbose_name='Archivo PDF (BLOB)')),
                ('filename', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('content_type', models.CharField(default='application/pdf', max_length=100, verbose_name='Tipo de Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado Generado',
                'verbose_name_plural': 'Certificados Generados',
                'ordering': ['-created_at'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
