# Generated by Django 5.2.7 on 2026-02-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evento_config_certificado_and_more'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS lugares_evento"),
        migrations.CreateModel(
            name='LugarEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción del Lugar')),
            ],
            options={
                'verbose_name': 'Lugar de Evento',
                'verbose_name_plural': 'Lugares de Evento',
                'db_table': 'lugares_evento',
                'ordering': ['descripcion'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_new', to='core.lugarevento', verbose_name='Lugar (Normalizado)'),
        ),
    ]
