# Generated by Django (Data Migration)

from django.db import migrations

def populate_locations(apps, schema_editor):
    Evento = apps.get_model('core', 'Evento')
    LugarEvento = apps.get_model('core', 'LugarEvento')
    
    # Iterate over all events
    for evento in Evento.objects.all():
        # Get the old string value
        if evento.lugar:
            lugar_str = evento.lugar.strip()
            # If string is not empty
            if lugar_str:
                # Get or create the LugarEvento object
                # Use get_or_create to avoid duplicates if multiple events share same location
                lugar_obj, created = LugarEvento.objects.get_or_create(descripcion=lugar_str)
                
                # Assign to the new FK field
                evento.lugar_new = lugar_obj
                evento.save()

def reverse_populate_locations(apps, schema_editor):
    # Reverse logic: Populate string field from FK
    Evento = apps.get_model('core', 'Evento')
    for evento in Evento.objects.all():
        if evento.lugar_new:
            evento.lugar = evento.lugar_new.descripcion
            evento.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lugarevento_evento_lugar_new'),
    ]

    operations = [
        migrations.RunPython(populate_locations, reverse_populate_locations),
    ]
