# Generated by Django 5.2.7 on 2026-02-13 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_populate_locations'),
    ]

    operations = [
        # 1. Remove the old CharField 'lugar'
        migrations.RemoveField(
            model_name='evento',
            name='lugar',
        ),
        # 2. Rename the new FK field 'lugar_new' to 'lugar'
        migrations.RenameField(
            model_name='evento',
            old_name='lugar_new',
            new_name='lugar',
        ),
        # 3. Alter the field to ensure all attributes (verbose_name, related_name) match the final model
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.lugarevento', verbose_name='Lugar'),
        ),
    ]
