# Generated by Django 5.2.7 on 2026-02-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_evento_lugar_new_alter_evento_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='cantidad_refrigerios',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='detalles_refrigerios',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='requiere_refrigerio',
        ),
        migrations.AddField(
            model_name='evento',
            name='cantidad_entregables',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de Entregables (Total)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='detalles_entregables',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalles de Entregables'),
        ),
        migrations.AddField(
            model_name='evento',
            name='requiere_entregable',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Entregable/Souvenir?'),
        ),
    ]
