# Generated by Django 5.2.4 on 2026-03-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_evento_cantidad_refrigerios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='enviar_difusion',
            field=models.BooleanField(default=False, verbose_name='Enviar Difusión Automática'),
        ),
    ]
