# Generated by Django 5.2.4 on 2026-03-10 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_evento_enviar_difusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_asignaciones', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_asignados', to='core.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_eventos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Staff')),
            ],
            options={
                'verbose_name': 'Staff de Evento',
                'verbose_name_plural': 'Staff de Eventos',
                'unique_together': {('evento', 'usuario')},
            },
        ),
    ]
